### PR TITLE
Advanced sql queries

### PR DESCRIPTION
**Pull request by ghost**
- Implemented Advanced SQL Queries (Joins and SubQuery)
- Video Link:- https://www.loom.com/share/208667eac4b14d76afba8fc3f15fdb46?sid=2e59435d-d6c7-4436-a239-af16eba7b5a8

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
hey @Itachi-789 the self-viva for `Advanced SQL Queries` the concept is not discussed thoroughly. please mention the different types of joins and explain about the uses of sub-queries. a demo of the same is also missing.

consider re-submitting with the appropriate additions.

**Review by th3c0d3br34ker — CHANGES_REQUESTED** [review]
hey @Itachi-789 the self-viva for `Advanced SQL Queries` the concept is not discussed thoroughly. please mention the different types of joins and explain about the uses of sub-queries. a demo of the same is also missing.

consider re-submitting with the appropriate additions.

**Comment by ghost** [comment]
> hey @Itachi-789 the self-viva for `Advanced SQL Queries` the concept is not discussed thoroughly. please mention the different types of joins and explain about the uses of sub-queries. a demo of the same is also missing.
> 
> consider re-submitting with the appropriate additions.

Okay, will try to resubmit the video today.

**Comment by th3c0d3br34ker** [comment]
please create separate PR again for this concept.

**Pull request merged**
