### PR TITLE
Added DDL / DML commands

### PR DESCRIPTION
**Pull request by ghost**
Video Links:- 
Milestone 2:- https://www.loom.com/share/f54000687e954993910c294a6d3bc083?sid=1d729f3e-3da3-49e2-92cb-f47e288e1d43

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
hey @Itachi-789 the self-viva missing. Please re-submit with the link attached.

Further more the milestone 1 submission was missing as well. please schedule a viva. the link for the same is available in the wiki.

thanks

**Comment by th3c0d3br34ker** [comment]
hey @Itachi-789 please add the link as a separate comment. it is hard to notice when you edit the previous comment.

**Comment by th3c0d3br34ker** [comment]
hey @Itachi-789 i reviewed your self-viva. 

the in-depth explanation for `DDL Commands` is missing.

please schedule a viva. the link for the same is available in the wiki.

thanks.

**Comment by ghost** [comment]
> hey @Itachi-789 i reviewed your self-viva.
> 
> the in-depth explanation for `DDL Commands` is missing.
> 
> please schedule a viva. the link for the same is available in the wiki.
> 
> thanks.

Okay, will schedule it along with the next viva only.

**Comment by th3c0d3br34ker** [comment]
@Itachi-789 please refrain from merging PR without approval

**Comment by th3c0d3br34ker** [comment]
as per our viva discussion: 
1. please submit an ERD and Schema.
2. re-submit on `kalvium.communiy`.
3. please re-submit DDL and DML commands as well.

**Pull request merged**
